package org.neo4j.cypherdsl.codegen.sdn6.models.valid.ids;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeImpl;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class InternalGeneratedId_ extends NodeImpl<InternalGeneratedId_> {
	public static final InternalGeneratedId_ INTERNAL_GENERATED_ID = new InternalGeneratedId_();

	public InternalGeneratedId_() {
		super("InternalGeneratedId");
	}

	private InternalGeneratedId_(SymbolicName symbolicName, List<NodeLabel> labels,
		Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public InternalGeneratedId_ named(SymbolicName newSymbolicName) {
		return new InternalGeneratedId_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public InternalGeneratedId_ withProperties(MapExpression newProperties) {
		return new InternalGeneratedId_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}