package org.neo4j.cypherdsl.codegen.sdn6.models.ids;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class InternalGeneratedPrimitiveLongId_ extends NodeBase<InternalGeneratedPrimitiveLongId_> {
	public static final String $PRIMARY_LABEL = "InternalGeneratedPrimitiveLongId";

	public static final InternalGeneratedPrimitiveLongId_ INTERNAL_GENERATED_PRIMITIVE_LONG_ID = new InternalGeneratedPrimitiveLongId_();

	public InternalGeneratedPrimitiveLongId_() {
		super($PRIMARY_LABEL);
	}

	private InternalGeneratedPrimitiveLongId_(SymbolicName symbolicName, List<NodeLabel> labels,
		Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public InternalGeneratedPrimitiveLongId_ named(SymbolicName newSymbolicName) {
		return new InternalGeneratedPrimitiveLongId_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public InternalGeneratedPrimitiveLongId_ withProperties(MapExpression newProperties) {
		return new InternalGeneratedPrimitiveLongId_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
