package org.neo4j.cypherdsl.codegen.sdn6.models.valid.ids;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class InternalGeneratedIdWithSpringId_ extends NodeBase<InternalGeneratedIdWithSpringId_> {
	public static final InternalGeneratedIdWithSpringId_ INTERNAL_GENERATED_ID_WITH_SPRING_ID = new InternalGeneratedIdWithSpringId_();

	public InternalGeneratedIdWithSpringId_() {
		super("InternalGeneratedIdWithSpringId");
	}

	private InternalGeneratedIdWithSpringId_(SymbolicName symbolicName, List<NodeLabel> labels,
		Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public InternalGeneratedIdWithSpringId_ named(SymbolicName newSymbolicName) {
		return new InternalGeneratedIdWithSpringId_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public InternalGeneratedIdWithSpringId_ withProperties(MapExpression newProperties) {
		return new InternalGeneratedIdWithSpringId_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}