package org.neo4j.cypherdsl.codegen.ogm.models.same_properties_for_rel_type;

import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2025-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class ActedIn_<E extends NodeBase<?>> extends RelationshipBase<Person_, E, ActedIn_<E>> {
	public static final String $TYPE = "ACTED_IN";

	public final Property ROLES = this.property("roles");

	public ActedIn_(Person_ start, E end) {
		super(start, $TYPE, end);
	}

	private ActedIn_(SymbolicName symbolicName, Node start, Properties properties,
		Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public ActedIn_<E> named(SymbolicName newSymbolicName) {
		return new ActedIn_<>(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public ActedIn_<E> withProperties(MapExpression newProperties) {
		return new ActedIn_<>(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
