package org.neo4j.cypherdsl.codegen.sdn6.models.labels.nodeswithdifferentlabelannotations;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
		value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
		date = "2019-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class LabelOnNode3_ extends NodeBase<LabelOnNode3_> {
	public static final LabelOnNode3_ LABEL_ON_NODE_3 = new LabelOnNode3_();

	public LabelOnNode3_() {
		super("ALabel");
	}

	private LabelOnNode3_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public LabelOnNode3_ named(SymbolicName newSymbolicName) {
		return new LabelOnNode3_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public LabelOnNode3_ withProperties(MapExpression newProperties) {
		return new LabelOnNode3_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}