package org.neo4j.cypherdsl.codegen.sdn6.models.valid.labels.nodeswithdifferentlabelannotations;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeImpl;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
		value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
		date = "2019-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class LabelOnNode2_ extends NodeImpl<LabelOnNode2_> {
	public static final LabelOnNode2_ LABEL_ON_NODE_2 = new LabelOnNode2_();

	public LabelOnNode2_() {
		super("ALabel");
	}

	private LabelOnNode2_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public LabelOnNode2_ named(SymbolicName newSymbolicName) {
		return new LabelOnNode2_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public LabelOnNode2_ withProperties(MapExpression newProperties) {
		return new LabelOnNode2_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
