package org.neo4j.cypherdsl.codegen.sdn6.models.labels.nodeswithdifferentlabelannotations;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
		value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
		date = "2019-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class LabelOnNode1_ extends NodeBase<LabelOnNode1_> {
	public static final LabelOnNode1_ LABEL_ON_NODE_1 = new LabelOnNode1_();

	public LabelOnNode1_() {
		super("ALabel");
	}

	private LabelOnNode1_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public LabelOnNode1_ named(SymbolicName newSymbolicName) {
		return new LabelOnNode1_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public LabelOnNode1_ withProperties(MapExpression newProperties) {
		return new LabelOnNode1_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}