package org.neo4j.cypherdsl.codegen.sdn6.models.labels.nodeswithdifferentlabelannotations;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder", date = "2019-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration.")
public final class MultipleLabels2_ extends NodeBase<MultipleLabels2_> {

	public static final String $PRIMARY_LABEL = "PL";

	public static final MultipleLabels2_ MULTIPLE_LABELS_2 = new MultipleLabels2_();

	public MultipleLabels2_() {
		super($PRIMARY_LABEL, "Label1", "Label2");
	}

	private MultipleLabels2_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public MultipleLabels2_ named(SymbolicName newSymbolicName) {
		return new MultipleLabels2_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public MultipleLabels2_ withProperties(MapExpression newProperties) {
		return new MultipleLabels2_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}

}
