== The Spring Data Neo4j 6 annotation processor

We provide a Java annotation processor for https://docs.spring.io/spring-data/neo4j/docs/current/reference/html/#reference[Spring Data Neo4j] under the following coordinates:

[source,subs="verbatim,attributes",indent=0,tabsize=4]
.Coordinates of the SDN 6 annotation processor
----
{groupId}:neo4j-cypher-dsl-codegen-sdn6:{neo4j-cypher-dsl-version}
----

The annotation processor understands classes annotated with `@Node` and `@RelationshipProperties`.
Inside those classes `@Relationship` and `@Property` are read.

The processor generates a static meta model for each annotated class found in the same package with an underscore (`_`) added to the name.

The processor needs Spring Data Neo4j 6 and the Cypher-DSL in version `2021.1.0` or later on it's classpath.
We recommend using it explicitly on the separate annotation processor classpath (via `--processor-path` to `javac`).

TIP: Please make sure to use `@Relationship` when you use the annotation processor. While we do our best to detect possible,
     implicit associations during annotation processing, we can't load classes that are being processed that very moment
     to check if the Spring infrastructure would provide a custom converter for them and make them a simple property.
     We won't generate fields when in doubt but relationships if we find the corresponding class.

=== Configure your build

==== Maven

As a Maven user, please configure the build as follows:

[source,xml,subs="verbatim,attributes",indent=0,tabsize=4]
----
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <annotationProcessorPaths>
                    <annotationProcessorPath>
                        <groupId>{groupId}</groupId>
                        <artifactId>neo4j-cypher-dsl-codegen-sdn6</artifactId>
                        <version>{neo4j-cypher-dsl.version}</version>
                    </annotationProcessorPath>
                </annotationProcessorPaths>
            </configuration>
        </plugin>
    </plugins>
</build>
----

==== Gradle

In a Gradle project, please add the following:

[source,groovy,subs="verbatim,attributes"]
----
dependencies {
    annotationProcessor '{groupId}:neo4j-cypher-dsl-codegen-sdn6:{neo4j-cypher-dsl-version}'
}
----

==== As dependency on the classpath

NOTE: We recommend the annotation processor path for two reasons: The processor needs SDN as dependency. While SDN is already on the classpath,
it might not fit the one we build the annotation processor against exactly.
While the processor is lenient in that regard, your dependency setup might not.
Furthermore: Why should you have the annotation processor as a dependency in your final artifact? This would be unnecessary.

If you insist on having the SDN 6 annotation processor on the standard class path, please include with your Spring Data Neo4j 6
application like as follows to avoid dependency conflicts:

[source,xml,subs="verbatim,attributes",indent=0,tabsize=4]
----
<dependency>
    <groupId>{groupId}</groupId>
    <artifactId>neo4j-cypher-dsl-codegen-sdn6</artifactId>
    <version>{neo4j-cypher-dsl.version}</version>
    <optional>true</optional>
    <exclusions>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-neo4j</artifactId>
        </exclusion>
    </exclusions>
</dependency>
----

=== Usage

The processor supports the following arguments:

|===
|Name | Meaning

| org.neo4j.cypherdsl.codegen.prefix,
| An optional prefix for the generated classes

| org.neo4j.cypherdsl.codegen.suffix
| An optional suffix for the generated classes

| org.neo4j.cypherdsl.codegen.indent_style
| The indent style (Use `TAB` for tabs, `SPACE` for spaces)

| org.neo4j.cypherdsl.codegen.indent_size
| The number of whitespaces for the indent style `SPACE`

| org.neo4j.cypherdsl.codegen.timestamp
| An optional timestamp in ISO_OFFSET_DATE_TIME format for the generated classes. Defaults to the time of generation.

| org.neo4j.cypherdsl.codegen.add_at_generated
| A flag whether `@Generated` should be added

| org.neo4j.cypherdsl.codegen.sdn.custom_converter_classes
| A comma separated list of custom Spring converter classes (Can be `Converter`, `GenericConverter`, `ConverterAware`,
  pretty much everything you can register with `org.springframework.data.neo4j.core.convert.Neo4jConversions` ). However,
  these converters must have a default-non-args constructor in the context of the annotation processor.

|===

The generated classes can be used in a variety of places:

[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/movies/MovieService.java[tag=as-property]
----
<.> Pass the name of the property `TITLE` to Spring Data's sort facility

Spring Data Neo4j 6.1 has two additional query fragments, that makes working with the Cypher-DSL very efficient:

[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/movies/PeopleRepository.java[tag=additional-fragments]
----
<.> Allows to just add conditions to our generated queries
<.> Provides an alternative to using @Query with strings

Both interfaces are *independent*  of each other, they can be used together like in this example or separately (just picking the one you need).
You can read more about them in the Spring Data Neo4j 6.1 documentation, chapter https://docs.spring.io/spring-data/neo4j/docs/6.1.0-M5/reference/html/#sdn-mixins[Spring Data Neo4j Extensions].

The repository above can be used like this:

[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/movies/PeopleService.java[tag=using-person-repo]
----
<.> Using literals
<.> Using an optional parameter
<.> or when it's not filled, an empty condition
<.> Project a person onto `PersonDetails`, using a complex query.

Here is another complex example. The `MovieRepository` is also a `CypherdslStatementExecutor`:

[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6/src/main/java/org/neo4j/cypherdsl/examples/sdn6/movies/MovieService.java[tag=more-examples]
----
<.> Here we use an anonymous parameter to store the `name` value

The full example is in `neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-sdn6`.
