== 2021.2

=== 2021.2.2

==== 🚀 Features

* Allow all expresions to be used as conditions. [improvement]
* Add support for unary minus and plus operations. [new-feature]
* Add support for generatic dynamic distinct aggregating function calls. [new-feature]
* GH-190 - Introduce a union type for named things and aliased expressions.
* Provide means to pass additional types to the relationship base class. [new-feature]
* GH-193 - Allow MATCH after YIELD.
* GH-189 - Provide an alternate api for methods consuming collections via vargs.

==== 📖 Documentation

* Improve inheritance example. [static-model, codegen]

==== 🐛 Bug Fixes

* Fix parameter collector when running as GraalVM native image
* GH-192 - Don't introduce new symbolic names in conditional pattern expressions.

==== 🧹 Housekeeping

* GH-178 - Upgrade SDN 6 examples to Spring Boot 2.5 final.

Thanks to https://github.com/meistermeier[@meistermeier] for the contribution of the API improvements in regard to collections.

=== 2021.2.1

==== 🚀 Features

* Distinguish between statements and result statements: The Cypher-DSL knows whether a statement would actually return
  data or not
* Provide optional integration with the Neo4j-Java-Driver to execute statements.
* Allow to register Spring converters with the annotation processor. [codegen]
* GH-182 - Add support for scalar converter functions.
* GH-183 - Add trim function.
* GH-184 - Add split function.
* GH-180 - Add support for LOAD CSV and friends.
* GH-187 - Add `returningRaw` for returning arbitrary (aliased) Cypher fragments (bot as part of a statement or as a
  general `RETURN xxx` clause without preceding query)
* Resolve named parameters in raw literals: You can mix now the expression placeholder `$E` and named parameters in raw
  Cypher literals giving you much more flexibility in regards what to pass to the raw litera.

==== 🐛 Bug Fixes

* GH-177 - Create a valid loadable and instantiable name when working on nested, inner classes. [codegen]
* GH-186 - Pretty print subqueries and fix double rendering of Labels after subquery.

==== 🧹 Housekeeping

* Remove unnecessary subpackage 'valid'. [codegen] (test code only)
* Upgrade to GraalVM 21.1.0.
* Update Spring dependencies for codegen.

Thanks to https://github.com/Andy2003[@Andy2003] for contributing to this release.

=== 2021.2.0

2021.2 doesn't bring any new features apart from being now a Java library supporting the Java module system not only with
automatic module names but also with a correct `module-info.java` when running on JDK 11+ on the module path.

The Cypher-DSL uses the technique of https://openjdk.java.net/jeps/238[JEP 238: Multi-Release JAR Files] to provide a
`module-info.java` for projects being on JDK 11+.

The MR-Jar allows us to compile for JDK 8 but also support JDK 11 (we choose 11 as it is the current LTS release as time of writing).

To use the Cypher-DSL in a modular application you would need to require the following modules:

[source,java]
----
module org.neo4j.cypherdsl.examples.core {

	requires org.neo4j.cypherdsl.core;
}
----

This release comes with a small catch: We do support using some https://github.com/querydsl/querydsl[QueryDSL] constructs.
Query-DSL will have correct automatic module names in their 5.x release and we asked them to backport those to the
4.x line on which the Cypher-DSL *optionally* depends (See https://github.com/querydsl/querydsl/pull/2805[2805]).

Until then we statically require (that is "optional" in module speak) Query-DSL via the artifact name.
This can cause errors when the artifact (`querydsl-core.jar`)  is renamed via the build process or similar.
We are gonna improve that as soon as we can depend on fixed automatic module names.

Apart from this big change there is no change in any public API.
This release should be a drop-in replacement for the prior release.

A big thank you to https://github.com/sormuras[@sormuras] for his invaluable lessons about the Java module system.
