== 2021.1

=== 2021.1.2

This release comes with two notable things: It uses a couple of annotations on the API to guide developers using it correctly.
IDEs like IDEA will now issue warnings if you don't use a returned builder, or a new instance of an object while wrongly assuming
you mutated state.

In the light of that we discovered that the `RelationshipChain` pattern was mutable and returning a mutated instance while
it should have returned a fresh one.

_Warning_ This might be a breaking change for users having code like this:

```
var pattern = Cypher.node("Start").named("s")
  .relationshipTo(Cypher.anyNode())
  .relationshipTo(Cypher.node("End").named("e"));
pattern.named("x");
```

Prior to 2021.1.2 this would give the pattern the name `x` and modify it in place.
From 2021.1.2 onwards you *must* use the returned value:

```
pattern = pattern.named("x");
```

We think that this change is crucial and necessary as all other patterns are immutable as intended and in sum, they build
up truly immutable statements. One pattern that is mutable like the above invalides the whole guarantee about the statement.

==== 🚀 Features

* Add `named(SymbolicName s)` to RelationshipChain.
* Generate $TYPE field containing the relationship type. [SDN 6 Annotation Processor]
* Introduce some optional annotations for guidance along the api.

==== 📖 Documentation

* GH-173 - Improve documentation. [A collection of small improvements]

==== 🐛 Bug Fixes

* GH-174 - Extract types via the visitor API and avoid casting element types. [SDN 6 Annotation Processor]
* Ensure immutability of `RelationshipChain`.

==== 🧹 Housekeeping

* Remove unnecessary close (will be taken care of via `@Container`). [Only test related]
* Run tests on JDK 16

=== 2021.1.1

This is a drop-in replacement for <<v2021.1.0>>. Introducing the interface for `Property` broke the `mutate` operation,
for which no test was in place. This and the bug has been fixed.

==== 🐛 Bug Fixes

* GH-168 - Fix mutating containers by properties.

[[v2021.1.0]]
=== 2021.1.0

2021.1.0 comes with a ton of new features and a handful of breaking changes.
Fear not, the breaking changes are resolvable by recompiling your application.
We turned `Node`, `Relationship` and `Property` into interfaces and provide now `NodeBase` and `RelationshipBase` so that you can
use them to build a static meta-model of your application. A `PropertyBase` might follow.

Find out everything about the new possibility to define a static meta model in <<static-meta-model,the manual>>.
The manual also includes a major part about the two new modules we offer:
`{groupId}:neo4j-cypher-dsl-codegen-core` and `{groupId}:neo4j-cypher-dsl-codegen-sdn6`.
`neo4j-cypher-dsl-codegen-core` provides the infrastructure necessary to build code generators for creating a domain model
following our recommendation and `neo4j-cypher-dsl-codegen-sdn6` is a first implementation of that:
A Java annotation processor that can be added to any Spring Data Neo4j 6 project in version 6.0.6 or higher.
It will find your annotated domain classes and turn them into a model you can use to build queries.

Last but not least: We added support for some expressions of the more generic http://www.querydsl.com[QueryDSL].
This will require `com.querydsl:querydsl-core` on the class path but only if you decide to call `Cypher#adapt(foreignExpression)`.
This is a feature that is driven by Spring Data Neo4j 6.1 in which we build upon this to provide a `QuerydslPredicateExecutor`.
Find more in <<query-dsl-support, this section of the manual>>.

==== 🚀 Features

* GH-154 - Make Node and Relationship extendable.
* GH-155 - Provide infrastructure for generating a static meta model.
* GH-156 - Create an annotation processor for Spring Data Neo4j 6.
* GH-167 - Add support for some Query-DSL expressions.
* Introduce a statement context for allowing anonymous parameters
  (use `Cypher#anonParameter()` to define a parameter with a value but without a name. The name will be accessible on the statement
  after rendering).
* Make rendering of constants as parameters configurable.
* Allow specification of the direction while creating a sort item.
* Introduce an interface for Property.

==== 📖 Documentation

* GH-152 - Document usage of PatterElement in tests.
* GH-164 - Improve public extendable API and add documentation.

==== 🐛 Bug Fixes

* Fix SymbolicName#toString.
* Clear visited name cache after single queries.

==== 🧹 Housekeeping

* GH-165 - Simplify poms.
* GH-166 - Improve Cypher.literalOf.
* Exclude all example projects from release.
