== 2024.5

=== 2024.5.0

This new minor release does not have any breaking changes.
A new dialect dubbed 5.26 has been introduced.
When configured, the renderer will prefix all queries with `CYPHER 5`, which is compatible with Neo4j 5.26 as well as the main line 2025.x.
It ensures that a future version of Neo4j will treat all queries generated with Cypher-DSL as Cypher 5, even when newer Cypher versions become available.

==== 🚀 Features

* Introduce Dialect 5.26 (#1185)

==== 🧹 Housekeeping

* Dependency upgrades:
** Bump testcontainers.version from 1.20.4 to 1.20.5 (#1184)
** Bump org.springframework.boot:spring-boot-starter-parent (#1183)
** Bump org.junit:junit-bom from 5.11.4 to 5.12.0 (#1182)
** Bump com.puppycrawl.tools:checkstyle (#1181)
** Bump io.projectreactor:reactor-bom (#1180)
** Bump org.springframework.data:spring-data-neo4j (#1179)
** Bump com.tngtech.archunit:archunit from 1.3.0 to 1.4.0 (#1178)

==== 🛠 Build

* fix: The default of `structuredMessage` is `false`. (Internal release announcer)
