== Building the Neo4j Cypher-DSL

=== Requirements

For the full project, including examples and native tests:

* GraalVM based on JDK 11: https://www.graalvm.org/downloads/

For the project, incuding examples but skipping native tests

* JDK 11+ (Can be https://openjdk.java.net[OpenJDK] or https://www.oracle.com/technetwork/java/index.html[Oracle JDK])

Only the core modules:

* JDK 8

* Maven 3.6.3 (We provide the Maven wrapper, see `mvnw` respectively `mvnw.cmd` in the project root; the wrapper downloads the appropriate Maven version automatically)

The build requires a local copy of the project:

[source,console,subs="verbatim,attributes"]
[[clone-cypher-dsl]]
.Clone the Neo4j Cypher-DSL
----
$ git clone git@github.com:neo4j-contrib/cypher-dsl.git
----

=== Full build (including examples and native tests)

Before you proceed, verify your locally installed JDK version.
The output should be similar:

[source,console,subs="verbatim,attributes"]
[[verify-jdk]]
.Verify your JDK
----
$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
----

Check whether GraalVM `native-image` is present with:

[source,console,subs="verbatim,attributes"]
[[verify-native-image]]
.Check for the present of `native-image`
----
$ gu list
ComponentId              Version             Component name                Stability           Origin
--------------------------------------------------------------------------------------------------------
js                       21.0.0              Graal.js                      -
graalvm                  21.0.0              GraalVM Core                  -
native-image             21.0.0              Native Image                  Early adopter       github.com
----

You should see `native-image in the list. If not, install it via `gu install native-image`.

After that, use `./mvnw` on a Unix-like operating system to build the Cypher-DSL:

[source,console,subs="verbatim,attributes"]
[[build-default-bash]]
.Build with default settings on Linux / macOS
----
$ ./mvnw clean verify
----

On a Windows machine, use

[source,console,subs="verbatim,attributes"]
[[build-default-windows]]
.Build with default settings on Windows
----
$ mvnw.cmd clean verify
----

=== Skipping native tests

On a plain JDK 11 or higher, run the following to skip the native tests:

[source,console,subs="verbatim,attributes"]
[[build-skip-native-bash]]
.Skipping native tests
----
$ ./mvnw clean verify -pl \!org.neo4j:neo4j-cypher-dsl-native-tests
----

=== Build only the core module

The core module can be build on plain JDK 8 with:

[source,console,subs="verbatim,attributes"]
[[build-only-core-bash]]
.Skipping native tests
----
$ ./mvnw clean verify -pl org.neo4j:neo4j-cypher-dsl
----
