== Query-DSL support

The Neo4j Cypher-DSL has some support for http://www.querydsl.com[Query-DSL]. It can

* turn instances of `com.querydsl.core.types.Predicate` into `org.neo4j.cypherdsl.core.Condition`,
* turn instances of `com.querydsl.core.types.Expression` into `org.neo4j.cypherdsl.core.Expression`,
* create `org.neo4j.cypherdsl.core.Node` instances from `com.querydsl.core.types.Path` and also
* create `org.neo4j.cypherdsl.core.SymbolicName`

With this, many static meta models based on Query-DSL can be used to create Queries and match on nodes.
Most operations supported by Query-DSL are translated into Cypher that is understood by Neo4j 4.0+, so that most predicates
should work - at least from a syntactic point of view - out of the box.

Expressions are most useful to address properties in return statements and the like.

Here's one example on how to use it:

[[appendix.query-dsl-support.query-dsl-simple]]
[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/querydsl/QueryDSLAdapterTest.java[tags=query-dsl-simple]
----
<.> This makes use of a "Q"-class generated by Query-DSL APT (using the general processor).
    `alias` and class based paths works, too.
    Please make sure to name the instance accordingly when you use it as node (see next step)
<.> Adapt the "Q"-class into a node. Please note it must be named accordingly, otherwise you query
    won't return the expected results
<.> Create some Query-DSL predicate based on the properties and adapt it as condition
<.> Return some Query-DSL properties and adapt it as expression

The `Statement` offers a way to render all constants as parameters, so that they don't bust the query cache:

[[appendix.query-dsl-support.query-dsl-simple-avoid-constants]]
[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/querydsl/QueryDSLAdapterTest.java[tags=query-dsl-simple-avoid-constants]
----
<.> Set this to true before accessing parameters of the statement or rendering the statement
<.> Access the statements parameters for generated parameter names
<.> Compare the statement to the first listening. Constants are gone now

The Neo4j Cypher-DSL will collect all parameters defined via Query-DSL for you:

[[appendix.query-dsl-support.query-dsl-parameters]]
[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/querydsl/QueryDSLAdapterTest.java[tags=query-dsl-parameters]
----
<.> Basically the same predicate as above, but with parameters, which will be turned into correct placeholders
<.> Access the parameter names via the `Statement` object

=== Required dependencies

The Query-DSL support in the Neo4j Cypher-DSL is optional, and the Query-DSL dependency is only in the `provided` scope.
To make use of `Cypher.adapt()`, you must add the following dependency in addition to the Cypher-DSL:

==== Maven

[source,xml]
----
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-core</artifactId>
    <version>4.4.0</version>
    <scope>provided</scope>
</dependency>
----

==== Gradle

[source,groovy]
----
dependencies {
    implementation 'com.querydsl:query-dsl-core:4.4.0'
}
----

In case you want to use an annotation processor, you have to add additional dependencies and depending on your Java environment.
We use the following in our tests:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-apt</artifactId>
        <version>4.4.0</version>
        <classifier>general</classifier>
    </dependency>
    <dependency>
        <groupId>javax.annotation</groupId>
        <artifactId>javax.annotation-api</artifactId>
        <version>1.3.2</version>
    </dependency>
</dependencies>
----
