package org.neo4j.cypherdsl.codegen.sdn6.models.simple;

import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Rel22_ extends RelationshipBase<Target2_, Src_, Rel22_> {
	public static final String $TYPE = "rel22";

	public Rel22_(Target2_ start, Src_ end) {
		super(start, $TYPE, end);
	}

	private Rel22_(SymbolicName symbolicName, Node start, Properties properties, Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public Rel22_ named(SymbolicName newSymbolicName) {
		return new Rel22_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public Rel22_ withProperties(MapExpression newProperties) {
		return new Rel22_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
