package org.neo4j.cypherdsl.codegen.sdn6.models.simple;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Src_ extends NodeBase<Src_> {
	public static final String $PRIMARY_LABEL = "Src";

	public static final Src_ SRC = new Src_();

	public final Property TITLE = this.property("title");

	public final Property DESCRIPTION = this.property("tagline").referencedAs("description");

	public final Property RELEASED = this.property("released");

	public Src_() {
		super($PRIMARY_LABEL);
	}

	private Src_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public Src_ named(SymbolicName newSymbolicName) {
		return new Src_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public Src_ withProperties(MapExpression newProperties) {
		return new Src_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
