package org.neo4j.cypherdsl.codegen.sdn6.models.simple;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Target2_ extends NodeBase<Target2_> {
	public static final String $PRIMARY_LABEL = "Target2";

	public static final Target2_ TARGET_2 = new Target2_();

	public final Property NAME = this.property("name");

	public final Property BORN = this.property("born");

	public final Rel22_ REL_2_2 = new Rel22_(this, Src_.SRC);

	public Target2_() {
		super($PRIMARY_LABEL);
	}

	private Target2_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public Target2_ named(SymbolicName newSymbolicName) {
		return new Target2_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public Target2_ withProperties(MapExpression newProperties) {
		return new Target2_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}

	public Rel21_ withRel21(Target2_ rel21) {
		return new Rel21_(this, rel21);
	}
}
