== Purpose

The Cypher-DSL has been developed with the needs of https://github.com/neo4j/sdn-rx[SDN/RX] in mind:
We wanted to avoid string concatenations in our query generation and decided do go with a builder approach, much like we
find with https://www.jooq.org[jOOQ] or in the relational module of https://github.com/spring-projects/spring-data-jdbc/tree/1.1.6.RELEASE/spring-data-relational/src/main/java/org/springframework/data/relational/core/sql[Spring Data JDBC], but for Cypher.

What we don't have - and don't need for our mapping purpose - at the moment is a code generator that reads the database schema
and generates static classes representing labels and relationship types.
That is still up to the mapping framework (in our case SDN/RX).
We however have a type safe API for Cypher that allows only generating valid Cypher constructs.

We worked closely with the https://www.opencypher.org[OpenCypher spec] here and you find a lot of these concepts in the API.

The Cypher-DSL can also be seen in the same area as the https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/query/Criteria.html[Criteria API] of Spring Data Mongo.

== Where to use it

The Cypher-DSL creates an https://en.wikipedia.org/wiki/Abstract_syntax_tree[Abstract Syntax Tree (AST)] representing your Cypher-Statements.
An instance of a `org.neo4j.cypherdsl.core.Statement` representing that AST is provided at the end of query building step.
A `Renderer` is then used to create literal Java-Strings.
Those can be used in any context supporting String-based queries, for example with the https://github.com/neo4j/neo4j-java-driver[Neo4j Java driver] or inside embedded procedures and of course with Spring Data's https://github.com/spring-projects/spring-data-neo4j/blob/master/src/main/java/org/springframework/data/neo4j/core/Neo4jClient.java[Neo4j-Client].

Parameters in the generated queries will use the `$form` and as such be compatible with all current versions of Neo4j.

Users of SDN/RX respectively SDN 6 can use the generated `org.neo4j.cypherdsl.core.Statement` directly with the `Neo4jTemplate` or the `ReactiveNeo4jTemplate`.
Both the imperative and the reactive variants allow the retrieval and counting of entities without rendering a String first,
for example through `Neo4jTemplate#findAll(Statement, Class<T>)`.

== Java API

Find the Java-API and a generated project info here: link:project-info/apidocs/index.html[API] and link:project-info/index.html[project info].
