package org.neo4j.cypherdsl.codegen.sdn6.models.self_referential;

import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class BelongsTo_ extends RelationshipBase<Example_, Example_, BelongsTo_> {
	public static final String $TYPE = "BELONGS_TO";

	public BelongsTo_(Example_ start, Example_ end) {
		super(start, $TYPE, end);
	}

	private BelongsTo_(SymbolicName symbolicName, Node start, Properties properties, Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public BelongsTo_ named(SymbolicName newSymbolicName) {
		return new BelongsTo_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public BelongsTo_ withProperties(MapExpression newProperties) {
		return new BelongsTo_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
