== Prepare dependencies

Please use a dependency management system. We recommend either Maven or Gradle.

=== Maven configuration

[source,xml,subs="verbatim,attributes"]
.Inclusion of the Neo4j Cypher-DSL in a Maven project
----
<dependency>
	<groupId>{groupId}</groupId>
	<artifactId>{artifactId}</artifactId>
	<version>{the-version}</version>
</dependency>
----

=== Gradle configuration

[source,groovy,subs="verbatim,attributes"]
.Inclusion of the Neo4j Cypher-DSL in a Gradle project
----
dependencies {
    implementation '{groupId}:{artifactId}:{the-version}'
}
----

[[how-to-use-it]]
== How to use it

You use the Cypher-DSL as you would write Cypher:
it allows to write down even complex Cypher queries from top to bottom in a type safe, compile time checked way.

The examples to follow are using JDK 11.
We find the `var` keyword especially appealing in such a DSL as the types returned by the DSL are much less important than
the further building methods they offer.

IMPORTANT: The AST parts and intermediate build steps are immutable. That is, the methods create new intermediate steps.
For example, you cannot reuse an `ExposesLimit` step, but have to use the returned object from its `skip` method.

An instance of a `org.neo4j.cypherdsl.core.Statement` is provided at the end of every query building step.
This `Statement` needs to be rendered into a string or passed to methods supporting it as input.

Please get an instance of the default renderer via `org.neo4j.cypherdsl.renderer.Renderer#getDefaultRenderer()`.
The renderer provides a single method `render` for rendering the AST into a string representation.

Furthermore, the `Statement` will collect parameter names and if provided, parameter values.
Parameter names and values are available after the statement has been built and can for example be used directly with
Neo4j-Java-Driver.

[[how-to-use-it.examples]]
=== Examples

The following examples are 1:1 copies of the queries you will find in the Neo4j browser after running `:play movies`.

They use the following imports:

.Imports needed for the examples to compile
[source, java]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-imports]
----

To match and return all the movie, build your statement like this:

.Simple match
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e1]
----
<.> Declare a variable storing your node labeled `Movie` and named `m`, so that you can
<.> reuse it in both the match and the return part.
<.> The `build` method becomes only available when a compilable Cypher statement can be rendered.

==== Find

Match all nodes with a given set of properties:

.Find the actor named "Tom Hanks"...
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e2]
----

Limit the number of returned things and return only one attribute

.Find 10 people...
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e4]
----

Create complex conditions

.Find movies released in the 1990s...
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e5]
----

==== Query

Build relationships

.List all Tom Hanks movies...
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e6]
----

.Who directed "Cloud Atlas"?
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e7]
----

.Tom Hanks' co-actors...
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e8]
----

.How people are related to "Cloud Atlas"...
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-e9]
----

==== Solve

.Movies and actors up to 4 "hops" away from Kevin Bacon
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-bacon]
----

==== Recommend

.Extend Tom Hanks co-actors, to find co-co-actors who haven't worked with Tom Hanks...
[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=cypher-dsl-r]
----

=== More features

[[retrieving-parameters]]
==== Retrieving parameters being defined

A placeholder for a parameter can be defined via `Cypher.parameter("param")`.
This placeholder will be rendered as `$param` and must be filled with the appropriate means of the environment you're working with.

In addition, an arbitrary value can be bound to the name via `Cypher.parameter("param", "a value")` or `Cypher.parameter("param").withValue("a value")`.
`NULL` is a valid value.
The Cypher-DSL will not use those values, but collect them for you.

The following example shows how to access them and how to use it:

[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=collecting-params]
----
<.> The names contain all placeholders, also those without a value
<.> The parameter map contains only parameters with defined values

If you define a parameter with conflicting values, a `ConflictingParametersException` will be thrown the moment you try to retrieve the collected parameters.

==== Using the default renderer

A statement can render itself as well:

[source, java]
----
var statement = Cypher.returning(literalTrue().as("t")).build();
var cypher = statement.getCypher();
assertThat(cypher).isEqualTo("RETURN true AS t");
----

This, together with <<retrieving-parameters, the above>>, makes the statement a complete accessor for a Cypher-statement and its parameters.

[[retrieving-identifiable-expressions]]
==== Retrieving identifiable expressions

The `Statement` as well as the intermediate build steps after defining a `WITH` or `RETURN` clause allow to retrieve identifiable expressions
via `getIdentifiableExpressions()`. All expressions identifiable via a name such as named nodes and relationships, symbolic names or aliased
expressions are included. In addition, properties are also available.

Those information can be used when dynamically building a query to verify the presence of required expressions
or use them for further refinement.

The feature plays well with the <<driver-integration,driver integration>> and could be directly used to define mapping functions.

Statements parsed via the optional <<cypher-parser,parser module>> are also able to return their identifiable expressions.
The use case here might be evaluating a statement defined by a user being parsed and then checked if everything required is returned.

==== Generating formatted Cypher

The Cypher-DSL can also format the generated Cypher to some extend.
The `Renderer` offers the overload `Renderer getRenderer(Configuration configuration)`, taking in an instance of `org.neo4j.cypherdsl.core.renderer.Configuration`.

Instances of `Configuration` are thread-safe and reusable.
The class offers a couple of static convenience methods for retrieving some variants.

[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=pretty-printing-examle]
----
<.> Get a "pretty printing" instance of the renderer configuration and retrieve a renderer based on it
<.> Enjoy formatted Cypher.

==== Escaping names

The default renderer in its default configuration will escape all names (labels and relationship types) by default.
So `Movie` becomes `++`Movie`++` and `ACTED_IN` becomes `++`ACTED_IN`++`.
If you don't want this, you can either create a dedicated configuration for a renderer with that setting turned off or use
the pretty printing renderer:

[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=escaping]
----

==== Inserting raw Cypher

`Cypher.raw` allows for creating arbitrary expressions from raw String literals.
Users discretion is advised:

[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-core/src/test/java/org/neo4j/cypherdsl/examples/core/CypherDSLExamplesTest.java[tag=raw-cypher]
----
<.> The Cypher-DSL doesn't support a dynamic lookup of properties on expression at the moment.
    We use a raw Cypher string with the placeholder `$E` which resolves to the symbolic name also passed to the `raw` function.

[[dialect-support]]
== Dialect support

There is limited dialect support. The default dialect `org.neo4j.cypherdsl.core.renderer.Dialect.DEFAULT` is Neo4j 4.4 and earlier whereas `org.neo4j.cypherdsl.core.renderer.Dialect.NEO4J_5` is designated to work with Neo4j 5.

The Neo4j 5 dialect will render some things differently:

* `org.neo4j.cypherdsl.core.Functions.distance` will be rendered as `point.distance` instead of just `distance`
* `elementId` will be rendered "as is"
* `EXISTS(n.property)` will be rendered as `n.property IS NOT NULL`

Additional features might be added.

NOTE: It is especially noteworthy that `elementId(node)` will be rendered as `toString(id(node))` with the default dialect. This is helpful for building queries that must work a) without deprecation warnings and b) on both Neo4j 4 and 5. Of course this is not portable and the returned values must only be used for comparison inside one statement. But Neo4j advices strongly against making the internal entity ids available outside a transaction (See https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-elementid[elementID]: "Outside of the scope of a single transaction, no guarantees are given about the mapping between ID values and elements.")

Here is one example how to use a dialect:

[source, java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/DialectIT.java[tag=dialect-example]
----

[[catalog-support]]
== Catalog support

The Cypher-DSL offers a catalog view on statements. After a statement has been build, a catalog can be retrieved like this:

.Using the statement catalog from a constructed statement
[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl/src/test/java/org/neo4j/cypherdsl/core/StatementCatalogBuildingVisitorTest.java[tag=catalog-example]
----

In the above example the catalog contains all labels and types used (`Movie`, `Person`, `ACTED_IN`) and all conditions
that involves a property of an entity combining the labels or types into a node or relationship. In addition, the catalog
contains the identifiable elements.

This becomes especially powerful when combining with the optional <<cypher-parser,parser module>>:

.Using the statement catalog from a parsed statement
[source,java,indent=0,tabsize=4]
----
include::../../neo4j-cypher-dsl-examples/neo4j-cypher-dsl-examples-parser/src/test/java/org/neo4j/cypherdsl/examples/parser/StatementCatalogBuildingVisitorViaParserTest.java[tag=catalog-example]
----
