package org.neo4j.cypherdsl.codegen.sdn6.models.records;

import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class RecordAsRelationship_ extends RelationshipBase<NodeWithRecordProperties_, RecordTarget_, RecordAsRelationship_> {
	public static final String $TYPE = "recordAsRelationship";

	public RecordAsRelationship_(NodeWithRecordProperties_ start, RecordTarget_ end) {
		super(start, $TYPE, end);
	}

	private RecordAsRelationship_(SymbolicName symbolicName, Node start, Properties properties,
		Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public RecordAsRelationship_ named(SymbolicName newSymbolicName) {
		return new RecordAsRelationship_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public RecordAsRelationship_ withProperties(MapExpression newProperties) {
		return new RecordAsRelationship_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
