package org.neo4j.cypherdsl.codegen.sdn6.models.records;

import java.util.List;
import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder", date = "2019-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration.")
public final class RecordTarget_ extends NodeBase<RecordTarget_> {

	public static final String $PRIMARY_LABEL = "RecordTarget";

	public static final RecordTarget_ RECORD_TARGET = new RecordTarget_();

	public final Property VALUE = this.property("value");

	public RecordTarget_() {
		super($PRIMARY_LABEL);
	}

	private RecordTarget_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public RecordTarget_ named(SymbolicName newSymbolicName) {
		return new RecordTarget_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public RecordTarget_ withProperties(MapExpression newProperties) {
		return new RecordTarget_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}

}
