package org.neo4j.cypherdsl.codegen.sdn6.models.same_properties_for_rel_type;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
		value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
		date = "2019-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Play_ extends NodeBase<Play_> {
	public static final String $PRIMARY_LABEL = "Play";
	public static final Play_ PLAY = new Play_();

	public final Property TITLE = this.property("title");

	public Play_() {
		super($PRIMARY_LABEL);
	}

	private Play_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public Play_ named(SymbolicName newSymbolicName) {
		return new Play_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public Play_ withProperties(MapExpression newProperties) {
		return new Play_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
