package org.neo4j.cypherdsl.codegen.ogm.models.ids;

import java.util.List;
import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2025-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class ExternalGeneratedId_ extends NodeBase<ExternalGeneratedId_> {
	public static final String $PRIMARY_LABEL = "ExternalGeneratedId";

	public static final ExternalGeneratedId_ EXTERNAL_GENERATED_ID = new ExternalGeneratedId_();

	public final Property ID = this.property("id");

	public ExternalGeneratedId_() {
		super($PRIMARY_LABEL);
	}

	private ExternalGeneratedId_(SymbolicName symbolicName, List<NodeLabel> labels,
		Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public ExternalGeneratedId_ named(SymbolicName newSymbolicName) {
		return new ExternalGeneratedId_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public ExternalGeneratedId_ withProperties(MapExpression newProperties) {
		return new ExternalGeneratedId_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
