/*
 * Copyright (c) 2019-2026 "Neo4j,"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.neo4j.cypherdsl.codegen.sdn6.models.bidi;

import java.util.List;
import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
    value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
    date = "2019-09-21T21:21:00+01:00",
    comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Element_ extends NodeBase<Element_> {
    public static final String $PRIMARY_LABEL = "Element";

    public static final Element_ ELEMENT = new Element_();

    public final Property ID = this.property("id");

    public final HasPathPoints_ POINTS = new HasPathPoints_(this, Point_.POINT);

    public Element_() {
        super($PRIMARY_LABEL);
    }

    private Element_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
        super(symbolicName, labels, properties);
    }

    @Override
    public Element_ named(SymbolicName newSymbolicName) {
        return new Element_(newSymbolicName, getLabels(), getProperties());
    }

    @Override
    public Element_ withProperties(MapExpression newProperties) {
        return new Element_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
    }
}
