package org.neo4j.cypherdsl.codegen.sdn6.models.bidi;

import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class HasPathPoints_ extends RelationshipBase<Element_, Point_, HasPathPoints_> {
	public static final String $TYPE = "HAS_PATH_POINTS";

	public HasPathPoints_(Element_ start, Point_ end) {
		super(start, $TYPE, end);
	}

	private HasPathPoints_(SymbolicName symbolicName, Node start, Properties properties, Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public HasPathPoints_ named(SymbolicName newSymbolicName) {
		return new HasPathPoints_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public HasPathPoints_ withProperties(MapExpression newProperties) {
		return new HasPathPoints_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}