package org.neo4j.cypherdsl.codegen.sdn6.models.bidi;

import java.util.List;
import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
    value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
    date = "2019-09-21T21:21:00+01:00",
    comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Point_ extends NodeBase<Point_> {
  public static final String $PRIMARY_LABEL = "Point";

  public static final Point_ POINT = new Point_();

  public Point_() {
    super($PRIMARY_LABEL);
  }

  private Point_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
    super(symbolicName, labels, properties);
  }

  @Override
  public Point_ named(SymbolicName newSymbolicName) {
    return new Point_(newSymbolicName, getLabels(), getProperties());
  }

  @Override
  public Point_ withProperties(MapExpression newProperties) {
    return new Point_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
  }
}