package org.neo4j.cypherdsl.codegen.ogm.models.simple;

import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
		value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
		date = "2025-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Follows_ extends RelationshipBase<Person_, Person_, Follows_> {
	public static final String $TYPE = "follows";

	public Follows_(Person_ start, Person_ end) {
		super(start, $TYPE, end);
	}

	private Follows_(SymbolicName symbolicName, Node start, Properties properties, Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public Follows_ named(SymbolicName newSymbolicName) {
		return new Follows_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public Follows_ withProperties(MapExpression newProperties) {
		return new Follows_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
