package org.neo4j.cypherdsl.codegen.ogm.models.different_properties_for_rel_type;

import javax.annotation.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.Property;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
		value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
		date = "2025-09-21T21:21:00+01:00",
		comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class ActedInPlay_ extends RelationshipBase<Person_, Play_, ActedInPlay_> {
	public static final String $TYPE = "ACTED_IN";

	public final Property ROLES = this.property("roles");

	public ActedInPlay_(Person_ start, Play_ end) {
		super(start, $TYPE, end);
	}

	private ActedInPlay_(SymbolicName symbolicName, Node start, Properties properties,
			Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public ActedInPlay_ named(SymbolicName newSymbolicName) {
		return new ActedInPlay_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public ActedInPlay_ withProperties(MapExpression newProperties) {
		return new ActedInPlay_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
