package org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.domain;

import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Abuses_<E extends NodeBase<?>> extends RelationshipBase<Company_, E, Abuses_<E>> {
	public static final String $TYPE = "ABUSES";

	public Abuses_(Company_ start, E end) {
		super(start, $TYPE, end);
	}

	private Abuses_(SymbolicName symbolicName, Node start, Properties properties, Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public Abuses_<E> named(SymbolicName newSymbolicName) {
		return new Abuses_<>(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public Abuses_<E> withProperties(MapExpression newProperties) {
		return new Abuses_<>(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
