package org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.application;

import java.util.List;
import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.domain.DomainEntity_;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class CompanyModel_ extends NodeBase<CompanyModel_> {
	public static final String $PRIMARY_LABEL = "Company";

	public static final CompanyModel_ COMPANY_MODEL = new CompanyModel_();

	public final In_ PLACE = new In_(this, PlaceModel_.PLACE_MODEL);

	public final Uses_ DOMAIN_ENTITY = new Uses_(this, DomainEntity_.DOMAIN_ENTITY);

	public CompanyModel_() {
		super($PRIMARY_LABEL);
	}

	private CompanyModel_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public CompanyModel_ named(SymbolicName newSymbolicName) {
		return new CompanyModel_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public CompanyModel_ withProperties(MapExpression newProperties) {
		return new CompanyModel_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
