package org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.domain;

import java.util.List;
import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class DomainEntity2_ extends NodeBase<DomainEntity2_> {
	public static final String $PRIMARY_LABEL = "DomainEntity2";

	public static final DomainEntity2_ DOMAIN_ENTITY_2 = new DomainEntity2_();

	public DomainEntity2_() {
		super($PRIMARY_LABEL);
	}

	private DomainEntity2_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public DomainEntity2_ named(SymbolicName newSymbolicName) {
		return new DomainEntity2_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public DomainEntity2_ withProperties(MapExpression newProperties) {
		return new DomainEntity2_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
