package org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.domain;

import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class In_ extends RelationshipBase<Company_, Place_, In_> {
	public static final String $TYPE = "IN";

	public In_(Company_ start, Place_ end) {
		super(start, $TYPE, end);
	}

	private In_(SymbolicName symbolicName, Node start, Properties properties, Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public In_ named(SymbolicName newSymbolicName) {
		return new In_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public In_ withProperties(MapExpression newProperties) {
		return new In_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
