package org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.application;

import java.util.List;
import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.NodeBase;
import org.neo4j.cypherdsl.core.NodeLabel;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.NodeImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class PlaceModel_ extends NodeBase<PlaceModel_> {
	public static final String $PRIMARY_LABEL = "Place";

	public static final PlaceModel_ PLACE_MODEL = new PlaceModel_();

	public PlaceModel_() {
		super($PRIMARY_LABEL);
	}

	private PlaceModel_(SymbolicName symbolicName, List<NodeLabel> labels, Properties properties) {
		super(symbolicName, labels, properties);
	}

	@Override
	public PlaceModel_ named(SymbolicName newSymbolicName) {
		return new PlaceModel_(newSymbolicName, getLabels(), getProperties());
	}

	@Override
	public PlaceModel_ withProperties(MapExpression newProperties) {
		return new PlaceModel_(getSymbolicName().orElse(null), getLabels(), Properties.create(newProperties));
	}
}
