package org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.application;

import javax.annotation.processing.Generated;
import org.neo4j.cypherdsl.codegen.sdn6.models.same_rel_different_package.domain.DomainEntity_;
import org.neo4j.cypherdsl.core.MapExpression;
import org.neo4j.cypherdsl.core.Node;
import org.neo4j.cypherdsl.core.Properties;
import org.neo4j.cypherdsl.core.RelationshipBase;
import org.neo4j.cypherdsl.core.SymbolicName;

@Generated(
	value = "org.neo4j.cypherdsl.codegen.core.RelationshipImplBuilder",
	date = "2019-09-21T21:21:00+01:00",
	comments = "This class is generated by the Neo4j Cypher-DSL. All changes to it will be lost after regeneration."
)
public final class Uses_ extends RelationshipBase<CompanyModel_, DomainEntity_, Uses_> {
	public static final String $TYPE = "USES";

	public Uses_(CompanyModel_ start, DomainEntity_ end) {
		super(start, $TYPE, end);
	}

	private Uses_(SymbolicName symbolicName, Node start, Properties properties, Node end) {
		super(symbolicName, start, $TYPE, properties, end);
	}

	@Override
	public Uses_ named(SymbolicName newSymbolicName) {
		return new Uses_(newSymbolicName, getLeft(), getDetails().getProperties(), getRight());
	}

	@Override
	public Uses_ withProperties(MapExpression newProperties) {
		return new Uses_(getSymbolicName().orElse(null), getLeft(), Properties.create(newProperties), getRight());
	}
}
